AVOID_REPEAT: "\uFF0C\u3002\uFF1A\uFF1F\uFF01"
CHAT_LANG: Chinese
CHAT_LEN_LONG: 150
CHAT_LEN_SHORT: 40
FLOAT_MODE: fp16
FREE_GEN_LEN: 200
GEN_TEMP: 1.0
GEN_TOP_P: 0.85
MODEL_NAME: RWKV-4-Pile-7B-EngChn-test4-20230116
NUM_PARA_GPUS: 2
QA_PROMPT: false
RUN_DEVICE: cuda
ctx_len: 1024
grad_cp: 0
head_qk: 0
my_pos_emb: 50277
pre_ffn: 0
vocab_size: 0
